server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 1
  maxMoney: 9999
  description: 最少要发${limit.minMoney}元, 最多可以发${limit.maxMoney}元

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.onemore-time.top/luckymoney?characterEncoding=utf-8
    username: o2o
    password: yanfeng666!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true